server:
  port: 0

spring:
  application:
    name: order-service
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mydb?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include:
          - refresh
          - busrefresh
          - health
          - beans
          - info
          - httpexchanges
          - metrics
          - prometheus
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      consume: B3
      produce: B3_MULTI
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"

logging:
  level:
    org.springframework.security: DEBUG
    com.errday.userservice.client: DEBUG

  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"