server:
  port: 8888

spring:
  application:
    name: config-service

  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///R:/IdeaProject/native-file-repo
        git:
          uri: https://github.com/javython999/spring-cloud-config
          default-label: main